version: '3.0'
services:
  mysql1:
    image: mysql:5.7
    container_name: mysql1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    environment:
      - COMPOSE_PROJECT_NAME=spark
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - net_hadoop


networks:
  net_hadoop:
    driver: bridge
